[project]
name = "ollama-mattermost-bot"
version = "0.1.0"
description = "Nix Ollama Chatbot for Mattermost"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mattermostdriver>=7.3.2",
    "requests>=2.32.5",
]
